live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.bright]
black = "#2e3436"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#73d216"
magenta = "#75507b"
red = "#cc0000"
white = "#ffffff"
yellow = "#edd400"

[colors.primary]
background = "#0E1010"
foreground = "#eeeeee"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "SauceCodePro Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"
title = "alacritty"

[window.dimensions]
columns = 110
lines = 40

[window.padding]
x = 0
y = 0
